import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../models/user_model.dart';
import '../models/trade_model.dart';
import '../models/broker_model.dart';
import '../models/strategy_model.dart';
import '../../core/constants/app_constants.dart';

/// Service for handling local storage operations
class StorageService {
  static late SharedPreferences _prefs;
  static late Box<UserModel> _userBox;
  static late Box<TradeModel> _tradesBox;
  static late Box<BrokerModel> _brokersBox;
  static late Box<StrategyModel> _strategiesBox;
  static late Box<PositionModel> _positionsBox;
  static late Box<dynamic> _settingsBox;

  /// Initialize storage service
  static Future<void> init() async {
    // Initialize SharedPreferences
    _prefs = await SharedPreferences.getInstance();

    // Register Hive adapters
    _registerAdapters();

    // Open Hive boxes
    await _openBoxes();
  }

  /// Register all Hive type adapters
  static void _registerAdapters() {
    // Register model adapters (generated by hive_generator)
    // These would be generated automatically
    // Hive.registerAdapter(UserModelAdapter());
    // Hive.registerAdapter(UserPreferencesAdapter());
    // Hive.registerAdapter(UserSubscriptionAdapter());
    // Hive.registerAdapter(TradeModelAdapter());
    // Hive.registerAdapter(TradeTypeAdapter());
    // Hive.registerAdapter(TradeStatusAdapter());
    // Hive.registerAdapter(OrderTypeAdapter());
    // Hive.registerAdapter(BrokerModelAdapter());
    // Hive.registerAdapter(BrokerTypeAdapter());
    // Hive.registerAdapter(BrokerSyncSettingsAdapter());
    // Hive.registerAdapter(PositionModelAdapter());
    // Hive.registerAdapter(PositionTypeAdapter());
    // Hive.registerAdapter(StrategyModelAdapter());
    // Hive.registerAdapter(StrategyTypeAdapter());
    // Hive.registerAdapter(StrategyRiskManagementAdapter());
  }

  /// Open all Hive boxes
  static Future<void> _openBoxes() async {
    _userBox = await Hive.openBox<UserModel>('users');
    _tradesBox = await Hive.openBox<TradeModel>(AppConstants.tradesBox);
    _brokersBox = await Hive.openBox<BrokerModel>(AppConstants.brokersBox);
    _strategiesBox = await Hive.openBox<StrategyModel>('strategies');
    _positionsBox = await Hive.openBox<PositionModel>('positions');
    _settingsBox = await Hive.openBox<dynamic>(AppConstants.settingsBox);
  }

  // SharedPreferences methods
  static Future<bool> setBool(String key, bool value) async {
    return await _prefs.setBool(key, value);
  }

  static bool? getBool(String key) {
    return _prefs.getBool(key);
  }

  static Future<bool> setString(String key, String value) async {
    return await _prefs.setString(key, value);
  }

  static String? getString(String key) {
    return _prefs.getString(key);
  }

  static Future<bool> setInt(String key, int value) async {
    return await _prefs.setInt(key, value);
  }

  static int? getInt(String key) {
    return _prefs.getInt(key);
  }

  static Future<bool> setDouble(String key, double value) async {
    return await _prefs.setDouble(key, value);
  }

  static double? getDouble(String key) {
    return _prefs.getDouble(key);
  }

  static Future<bool> setStringList(String key, List<String> value) async {
    return await _prefs.setStringList(key, value);
  }

  static List<String>? getStringList(String key) {
    return _prefs.getStringList(key);
  }

  static Future<bool> remove(String key) async {
    return await _prefs.remove(key);
  }

  static Future<bool> clear() async {
    return await _prefs.clear();
  }

  // User operations
  static Future<void> saveUser(UserModel user) async {
    await _userBox.put('current_user', user);
  }

  static UserModel? getCurrentUser() {
    return _userBox.get('current_user');
  }

  static Future<void> clearUser() async {
    await _userBox.delete('current_user');
  }

  // Trade operations
  static Future<void> saveTrade(TradeModel trade) async {
    await _tradesBox.put(trade.id, trade);
  }

  static Future<void> saveTrades(List<TradeModel> trades) async {
    final Map<String, TradeModel> tradeMap = {
      for (var trade in trades) trade.id: trade
    };
    await _tradesBox.putAll(tradeMap);
  }

  static TradeModel? getTrade(String id) {
    return _tradesBox.get(id);
  }

  static List<TradeModel> getAllTrades() {
    return _tradesBox.values.toList();
  }

  static List<TradeModel> getTradesBySymbol(String symbol) {
    return _tradesBox.values.where((trade) => trade.symbol == symbol).toList();
  }

  static List<TradeModel> getTradesByStrategy(String strategy) {
    return _tradesBox.values.where((trade) => trade.strategy == strategy).toList();
  }

  static List<TradeModel> getTradesByDateRange(DateTime start, DateTime end) {
    return _tradesBox.values.where((trade) {
      return trade.entryTime.isAfter(start) && trade.entryTime.isBefore(end);
    }).toList();
  }

  static Future<void> deleteTrade(String id) async {
    await _tradesBox.delete(id);
  }

  static Future<void> clearAllTrades() async {
    await _tradesBox.clear();
  }

  // Broker operations
  static Future<void> saveBroker(BrokerModel broker) async {
    await _brokersBox.put(broker.id, broker);
  }

  static BrokerModel? getBroker(String id) {
    return _brokersBox.get(id);
  }

  static List<BrokerModel> getAllBrokers() {
    return _brokersBox.values.toList();
  }

  static List<BrokerModel> getConnectedBrokers() {
    return _brokersBox.values.where((broker) => broker.isConnected).toList();
  }

  static Future<void> deleteBroker(String id) async {
    await _brokersBox.delete(id);
  }

  // Strategy operations
  static Future<void> saveStrategy(StrategyModel strategy) async {
    await _strategiesBox.put(strategy.id, strategy);
  }

  static StrategyModel? getStrategy(String id) {
    return _strategiesBox.get(id);
  }

  static List<StrategyModel> getAllStrategies() {
    return _strategiesBox.values.toList();
  }

  static List<StrategyModel> getActiveStrategies() {
    return _strategiesBox.values.where((strategy) => strategy.isActive).toList();
  }

  static Future<void> deleteStrategy(String id) async {
    await _strategiesBox.delete(id);
  }

  // Position operations
  static Future<void> savePosition(PositionModel position) async {
    await _positionsBox.put(position.id, position);
  }

  static Future<void> savePositions(List<PositionModel> positions) async {
    final Map<String, PositionModel> positionMap = {
      for (var position in positions) position.id: position
    };
    await _positionsBox.putAll(positionMap);
  }

  static PositionModel? getPosition(String id) {
    return _positionsBox.get(id);
  }

  static List<PositionModel> getAllPositions() {
    return _positionsBox.values.toList();
  }

  static List<PositionModel> getPositionsByBroker(String brokerId) {
    return _positionsBox.values
        .where((position) => position.brokerId == brokerId)
        .toList();
  }

  static Future<void> deletePosition(String id) async {
    await _positionsBox.delete(id);
  }

  static Future<void> clearAllPositions() async {
    await _positionsBox.clear();
  }

  // Settings operations
  static Future<void> saveSetting(String key, dynamic value) async {
    await _settingsBox.put(key, value);
  }

  static T? getSetting<T>(String key) {
    return _settingsBox.get(key) as T?;
  }

  static Future<void> deleteSetting(String key) async {
    await _settingsBox.delete(key);
  }

  // Database maintenance
  static Future<void> compactBoxes() async {
    await _userBox.compact();
    await _tradesBox.compact();
    await _brokersBox.compact();
    await _strategiesBox.compact();
    await _positionsBox.compact();
    await _settingsBox.compact();
  }

  static Future<void> closeBoxes() async {
    await _userBox.close();
    await _tradesBox.close();
    await _brokersBox.close();
    await _strategiesBox.close();
    await _positionsBox.close();
    await _settingsBox.close();
  }

  // Backup and restore
  static Map<String, dynamic> exportData() {
    return {
      'user': getCurrentUser()?.toJson(),
      'trades': getAllTrades().map((t) => t.toJson()).toList(),
      'brokers': getAllBrokers().map((b) => b.toJson()).toList(),
      'strategies': getAllStrategies().map((s) => s.toJson()).toList(),
      'positions': getAllPositions().map((p) => p.toJson()).toList(),
      'settings': _settingsBox.toMap(),
      'exportedAt': DateTime.now().toIso8601String(),
    };
  }

  static Future<void> importData(Map<String, dynamic> data) async {
    // Clear existing data
    await clearAllTrades();
    await _brokersBox.clear();
    await _strategiesBox.clear();
    await clearAllPositions();
    await _settingsBox.clear();
    await clearUser();

    // Import user
    if (data['user'] != null) {
      final user = UserModel.fromJson(data['user']);
      await saveUser(user);
    }

    // Import trades
    if (data['trades'] != null) {
      final trades = (data['trades'] as List)
          .map((t) => TradeModel.fromJson(t))
          .toList();
      await saveTrades(trades);
    }

    // Import brokers
    if (data['brokers'] != null) {
      final brokers = (data['brokers'] as List)
          .map((b) => BrokerModel.fromJson(b))
          .toList();
      for (final broker in brokers) {
        await saveBroker(broker);
      }
    }

    // Import strategies
    if (data['strategies'] != null) {
      final strategies = (data['strategies'] as List)
          .map((s) => StrategyModel.fromJson(s))
          .toList();
      for (final strategy in strategies) {
        await saveStrategy(strategy);
      }
    }

    // Import positions
    if (data['positions'] != null) {
      final positions = (data['positions'] as List)
          .map((p) => PositionModel.fromJson(p))
          .toList();
      await savePositions(positions);
    }

    // Import settings
    if (data['settings'] != null) {
      final settings = data['settings'] as Map<String, dynamic>;
      for (final entry in settings.entries) {
        await saveSetting(entry.key, entry.value);
      }
    }
  }
}

